/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error': '#ba1a1a',
        'surface': '#fdf9f3',
        'inverse-primary': '#ffb783',
        'surface-dim': '#dddad4',
        'on-tertiary-fixed-variant': '#5a4300',
        'outline': '#887365',
        'on-secondary-fixed-variant': '#7c2e00',
        'outline-variant': '#dbc2b2',
        'secondary-container': '#fc7127',
        'primary-fixed-dim': '#ffb783',
        'on-secondary': '#ffffff',
        'on-primary-container': '#602e00',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#ffb595',
        'on-primary': '#ffffff',
        'on-surface': '#1c1c18',
        'on-tertiary-fixed': '#251a00',
        'tertiary': '#785a00',
        'background': '#fdf9f3',
        'on-secondary-container': '#5c2000',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#f8be00',
        'primary-container': '#f68a2f',
        'on-surface-variant': '#554337',
        'on-primary-fixed-variant': '#713700',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3ed',
        'surface-container-high': '#ebe8e2',
        'surface-container': '#f1ede7',
        'primary': '#944a00',
        'inverse-surface': '#31302d',
        'surface-tint': '#944a00',
        'surface-variant': '#e6e2dc',
        'tertiary-container': '#d09e00',
        'inverse-on-surface': '#f4f0ea',
        'primary-fixed': '#ffdcc5',
        'secondary': '#a23f00',
        'secondary-fixed': '#ffdbcd',
        'surface-container-highest': '#e6e2dc',
        'tertiary-fixed': '#ffdf9a',
        'on-error': '#ffffff',
        'on-tertiary-container': '#4c3800',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#351000',
        'on-primary-fixed': '#301400',
        'surface-bright': '#fdf9f3',
        'on-background': '#1c1c18',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Manrope', 'sans-serif'],
        'label': ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}